const image = require("../assets/images/listing-image.png");

export const listings = [
  {
    id: 1,
    name: "PlayStation Remote Player",
    image: image,
    price: "$140",
    openChats: "6",
    messageRequests: "14",
    status: "listed",
    type: "Active",
  },
  {
    id: 2,
    name: "PlayStation Remote Player",
    image: image,
    price: "$140",
    openChats: "6",
    messageRequests: "14",
    status: "listed",
    type: "Active",
  },
  {
    id: 3,
    name: "PlayStation Remote Player",
    image: image,
    price: "$140",
    openChats: "6",
    messageRequests: "14",
    status: "listed",
    type: "Active",
  },
  {
    id: 4,
    name: "PlayStation Remote Player",
    image: image,
    price: "$140",
    openChats: "6",
    status: "listed",
    type: "Tasks",
    messageRequests: "14",
  },
  {
    id: 5,
    name: "PlayStation Remote Player",
    image: image,
    price: "$140",
    openChats: "6",
    status: "listed",
    type: "Tasks",
    messageRequests: "14",
  },
  {
    id: 6,
    name: "PlayStation Remote Player",
    image: image,
    price: "$140",
    openChats: "6",
    status: "Unlisted",
    type: "Previous",
    messageRequests: "14",
  },
  {
    id: 7,
    name: "PlayStation Remote Player",
    image: image,
    price: "$140",
    openChats: "6",
    status: "Sold",
    type: "Previous",
    messageRequests: "14",
  },
];
